[package]
name    = "language-model-proxy-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-openai = { path = "vendored-deps/async-openai" }
axum = "0.7.4"
hyper = { version = "1", features = [
	"full",
] }
tokio = { version = "1", features = [
	"full",
] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = [
	"full",
] }
serde = { version = "1.0", features = [
	"derive",
] }
serde_json = "1.0"
toml = "0.8.8"



tower = { version = "0.4", features = [
	"make",
] }
tower-http = { version = "0.5", features = [
	"full",
] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
	"env-filter",
] }

reqwest = { version = "0.11", features = [
	"json",
] }

governor = "0.6"

uuid = { version = "1.7", features = [
	"v7",
	"serde",
] }
priority-queue = "1.3"
